title: Archer's workplaces
url: https://zxchcyc.github.io/

show_downloads: true
google_analytics: UA-92698003-1

theme: jekyll-theme-leap-day

gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
- README.md

